version: '3.9'

services:
  db:
    image: mysql:8.4.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE='tutorial08'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='password'
      - MYSQL_HOST='35.238.216.214'
      - MYSQL_ROOT_PASSWORD='password'
    volumes:
      - /tmp/code/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - /tmp/code/mysqld:/run/mysqld
    depends_on:
      - db